name    'aggressivex-atlassian'
version '0.2.0'
author  'Luis M. Hdez'
license 'MIT'
project_page 'http://opensource.aggressivex.com/puppet/atlassian'
source  'https://github.com/aggressivex/puppet-atlassian'
summary 'Puppet module for atlassian tools'
description 'This module installs and manages atlassian tools.'
